server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: trade-service
          uri: lb://trade-service
          predicates:
            - Path=/trades/**
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customers/**
        - id: stock-service
          uri: lb://stock-service
          predicates:
            - Path=/stocks/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: localhost