server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customerdb
    username: ujwal
    password: ujwal
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: localhost
