spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: trade-service
          uri: http://localhost:8083
          predicates:
            - Path=/trades/**
        - id: customer-service
          uri: http://localhost:8081
          predicates:
            - Path=/customers/**
        - id: stock-service
          uri: http://localhost:8080
          predicates:
            - Path=/stocks/**
server:
  port: 8082