server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ujwal-rahile/config-repo.git
          clone-on-start: true